framework:
    messenger:
        default_bus: 'command.bus'
        buses:
            command.bus:
                middleware:
                    - 'doctrine_ping_connection'
                    - 'doctrine_close_connection'
                    - 'validation'
                    - 'doctrine_transaction'

            query.bus:
                middleware:
                    - 'doctrine_ping_connection'
                    - 'doctrine_close_connection'
                    - 'validation'

        transports:

        routing:
