services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Cli\:
        resource: '../src/Cli'

    App\Command\:
        resource: '../src/Command/**/*Handler.php'
        autoconfigure: false
        tags:
            - { name: 'messenger.message_handler', bus: 'command.bus' }

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Exception\:
        resource: '../src/Exception'

    App\Form\:
        resource: '../src/Form'
        exclude:
            - '../src/Form/Dto'

    App\Query\:
        resource: '../src/Query/**/*Handler.php'
        autoconfigure: false
        tags:
            - { name: 'messenger.message_handler', bus: 'query.bus' }

    Symfony\Component\HttpFoundation\Session\Storage\Handler\NullSessionHandler: ~
